version: '2'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - /usr/src/app/static
      - ./pickles:/usr/src/app/pickles
      - ./ml_models:/usr/src/app/ml_models
      - ./dataset:/user/src/app/dataset
      - /usr/local/lib/python3.5/site-packages/spacy/data

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web
