version: '2'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - /usr/src/app/static
      - /usr/src/app/pickles
      - /usr/src/app/ml_models

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web
